<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findOrderByName()
    {
        return $this->getEntityManager()
                ->createQuery('SELECT p FROM AppBundle:Product p ORDER BY p.name ASC')                
                ->getResult();        
    }
}
